[package]
name = "texture-looper"
version = "0.1.0"
authors = ["Bridger Herman"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
base64 = "0.10"
png = "0.14"
wasm-logger = { git = "https://github.com/bridger-herman/wasm-logger" }
log = "0.4"
